// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7diuoGR36dwdvReaHM62J7em-0hHWTE8',
    appId: '1:737729217306:web:362aee0bc7499aede122a3',
    messagingSenderId: '737729217306',
    projectId: 'charity-app-a4357',
    authDomain: 'charity-app-a4357.firebaseapp.com',
    storageBucket: 'charity-app-a4357.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZI-l4AUmHDZ97YOOXjzUod2ZnXLK-lk',
    appId: '1:737729217306:android:32f25cc12372830fe122a3',
    messagingSenderId: '737729217306',
    projectId: 'charity-app-a4357',
    storageBucket: 'charity-app-a4357.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjUIxBWbXE42yIxF0CpK-D-BCfsLl05bY',
    appId: '1:737729217306:ios:e32cc9918f5de5dde122a3',
    messagingSenderId: '737729217306',
    projectId: 'charity-app-a4357',
    storageBucket: 'charity-app-a4357.firebasestorage.app',
    iosBundleId: 'hr.algebra.charityApp',
  );
}
